### ISSUE TITLE
New List Suggestion

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [QWIILXEY/filterlist-collection#1]
https://github.com/ammnt/DeadEnd

**Comment by KnightmareVIIVIIXC** [comment]
And if you really wanna break stuff: https://github.com/KnightmareVIIVIIXC/bigaioblocklist

**Comment by KnightmareVIIVIIXC** [comment]
And this: https://github.com/WilliDieEnte/BetterBlocklist

**Comment by QWIILXEY** [comment]
i added some of them (mainly better blocklist and dead end) thanks for the suggestion
